project:
  type: website
  output-dir: docs

website:
  title: "Elizabeth Pankratz"
  site-url: https://elizabethpankratz.github.io
  description: "I study how people learn linguistic structure and how this process affects language."
  favicon: imgs/ep-hsts.png
  navbar:
    right:
      - text: Home
        href: index.qmd
      - text: Research
        href: publications.qmd
      - text: Teaching
        href: teaching.qmd
      - text: Blog
        href: blog.qmd
      - text: CV
        href: documents/cv_engl.pdf

format:
  html:
    theme: flatlymod.scss
    css: styles.css



