project:
  type: website

website:
  title: "Elizabeth Pankratz"
  site-url: https://elizabethpankratz.github.io
  description: "I study how people learn linguistic structure and how this process affects language."
  navbar:
    right:
      - text: Home
        href: index.qmd
      - text: Publications
        href: publications.qmd
      - text: Teaching
        href: teaching.qmd
      - text: Blog
        href: blog.qmd
      - text: CV
        href: cv_engl.pdf

format:
  html:
    theme: flatlymod.scss
    css: styles.css



