project:
  type: website
  output-dir: docs

website:
  title: "Dr. Elizabeth Pankratz"
  site-url: https://elizabethpankratz.github.io
  description: "I teach statistics and study how people learn linguistic structure."
  favicon: imgs/ep-hsts.png
  navbar:
    right:
      - text: Bio
        href: bio.qmd
      - text: Teaching
        href: teaching.qmd
      - text: Research
        href: research.qmd
      - text: Supervision
        href: supervision.qmd
      - text: Blog
        href: blog.qmd
      - text: CV
        href: documents/cv_engl.pdf

format:
  html:
    theme: flatlymod.scss
    css: styles.css



