---
toc: true
---

# Supervision

In 2025–2026, I'm available to supervise UG and PG dissertations.

I enjoy exploring how people learn and generalise---how they move from concrete surface representations (like words and chunks) to more abstract ones (like rules and patterns).
Most of my work has focused on language, but I'm also happy to supervise projects on learning more broadly.

Please do get in touch if you're interested in working with me on any of the following topics:

- word segmentation
- rule learning
- rule generalisation
- neurodiversity (esp. autism) and its impact on word/rule learning
- scholarship of teaching and learning


Methods I'm happy to supervise:

- behavioural experiments (especially psycholinguistic methods and artificial language learning)
- corpus studies
- computational modelling and simulation
- statistical analysis, both frequentist and Bayesian


# Resources for supervisees

### Managing your literature

- A blog post on [organising notes on academic literature using a synthesis matrix](https://elizabethpankratz.github.io/posts/01-phd-litreview/) which I wrote during my PhD.
- UoE guidance on [reference management tools](https://edinburgh-uk.libguides.com/referencing).
  - I like [Zotero](https://www.zotero.org/support/quick_start_guide).
  - UoE likes [EndNote](https://information-services.ed.ac.uk/computing/desktop-personal/software/main-software-deals/endnote).
  
<!-- ### Designing your experiment -->

<!-- - [Excellent slides on developing an experiment](https://www.overleaf.com/project/61893e79109b4671090a1b3d) by [Prof. Jennifer Culbertson](https://jennifer-culbertson.github.io). -->

  
<!-- ### Structuring your dissertation -->

<!-- - More excellent slides by [Prof. Jennifer Culbertson](https://jennifer-culbertson.github.io) on: -->
<!--   - the [anatomy of an academic article](https://www.overleaf.com/read/tncxzwhxwjqm#32dac2), and the same applies to a dissertation. -->
<!--   - the [anatomy of an abstract](https://www.overleaf.com/project/6180eac35af212e4fc9d1fe4). -->
<!--   - [how to report results](https://www.overleaf.com/project/61a619a5e834813ea3b6a932) (though note that for us, the quantitative analysis isn't optional!) -->
<!-- - Coming soon: How to structure academic writing using principles from storytelling (blog post) -->


### Finding your writerly voice

- I like to reread these books every couple years:
  - [Style: Toward Clarity and Grace](https://www.goodreads.com/book/show/246853.Style) by Joseph M. Williams (1990)
  - [Stylish Academic Writing](https://www.goodreads.com/book/show/13540208-stylish-academic-writing) by Helen Sword (2012)
- Coming soon: A walkthrough of my favourite way to plan, draft, and revise a piece of writing (blog post)


# Previous supervisees

[Sigurd Farstad Iversen](https://sigurdfarstad.github.io) (MSc Evolution of Language and Cognition, 2023)
