{
  "hash": "04cc14ac7e4570a04ec1d94056d2ca0b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"It takes 242,516 minutes to do a PhD\"\ndate: \"2025-04-16\"\ncategories: [PhD]\nimage: \"imgs/proj-hrs.png\"\ntoc: true\nformat:\n  html:\n    code-fold: true\n    code-tools: true\n---\n\n\nThat's 4041 hours and 56 minutes!\nI tracked all my work time during the PhD, and now that it's done, I can finally crunch the numbers.\n\n\n# The data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(patchwork)\n\ntheme_set(theme_bw())\ntheme_update(\n  text = element_text(family = \"Fira Sans\", size = 12),\n  panel.grid = element_blank(),\n  strip.background = element_blank(),\n  axis.title.y = element_text(angle = 0, vjust = 0.5, hjust = 0)\n)\n\npalette_year <- c(\"#51b375\", \"#ff94b0\", \"#1c4a86\", \"#ed7a1d\")\npalette_tasktype <- c(\"#1c4a86\",\"#51b375\", \"#FFCD29\", \"#3173c9\", \"#bb3725\")\npalette_proj <- c(\"#bb3725\", \"#FFCD29\",\"#51b375\", \"#3173c9\")\npalette_exam <- c(\"#1c4a86\", \"#bb3725\")\n\n# Read in the data and display first few rows.\nhrs <- read_csv('data/hrs.csv') |>\n  mutate(\n    year_idx  = factor(year_idx),\n    year      = factor(year)\n  )\nhead(hrs) |>\n  knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n|date       | mins|tasklabel      |tasktype  | week_idx| month_idx|year_idx |year |\n|:----------|----:|:--------------|:---------|--------:|---------:|:--------|:----|\n|2021-09-09 |   80|Reading groups |Community |        1|         1|1        |2021 |\n|2021-09-09 |   32|PhD admin      |Admin     |        1|         1|1        |2021 |\n|2021-09-09 |  118|PhD admin      |Admin     |        1|         1|1        |2021 |\n|2021-09-10 |   24|PhD admin      |Admin     |        1|         1|1        |2021 |\n|2021-09-13 |  105|PhD admin      |Admin     |        2|         1|1        |2021 |\n|2021-09-13 |   60|PhD admin      |Admin     |        2|         1|1        |2021 |\n\n\n:::\n:::\n\n\n&nbsp;\n\nThis dataset contains only the time I spent on core PhD tasks.\nAll my non-PhD collaborations and side projects have been filtered out.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nsum(hrs$mins)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 242516\n```\n\n\n:::\n:::\n\n\nFrom attending my first reading group on September 9, 2021, to submitting my thesis corrections on April 9, 2025, I worked on the PhD for 242,516 minutes.\n\n(And if reading that makes the song from RENT start playing in your head, you are not alone 🙈)\n\n\n# How many hours per day?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nyear_labs <- tibble(\n  date = c(\n    as.Date('28/02/2022', \"%d/%m/%Y\"),\n    as.Date('28/02/2023', \"%d/%m/%Y\"),\n    as.Date('28/02/2024', \"%d/%m/%Y\"),\n    as.Date('31/12/2024', \"%d/%m/%Y\")\n    ),\n  daily_hrs = 13.5,\n  lab = paste('Year', 1:4),\n  year_idx = factor(1:4)\n)\n\nhrs_daily <- hrs |>\n  group_by(date, year_idx) |>\n  summarise(\n    daily_hrs = sum(mins)/60,\n  )\n\np_daily_point <- hrs_daily |>\n  ggplot(aes(x = date, y = daily_hrs, colour = year_idx)) +\n  geom_point(alpha = 0.5) +\n  geom_smooth(method = 'lm', se = FALSE, linewidth = 2) +\n  geom_text(data = year_labs, aes(label = lab), family = 'Fira Sans', size = 4) +\n  labs(\n    y = 'Hours/\\nday',\n    x = element_blank(),\n    colour = 'Year of the PhD'\n  ) +\n  theme(legend.position = 'none') +\n  scale_colour_manual(values = palette_year) +\n  scale_y_continuous(breaks = seq(0, 12, 3), limits = c(0, 14)) +\n  NULL\n\np_daily_violin <- hrs_daily |>\n  ggplot(aes(x = year_idx, y = daily_hrs, colour = year_idx, fill = year_idx)) +\n  geom_violin(alpha = 0.5) +\n  geom_jitter(alpha = 0.5, width = 0.1) +\n  scale_fill_manual(values = palette_year) +\n  scale_colour_manual(values = palette_year) +\n  scale_x_discrete(labels = paste('Year', 1:4)) +\n  theme(legend.position = 'none') +\n  labs(\n    y = 'Hours/\\nday',\n    x = element_blank()\n  ) +\n  NULL\n\np_daily_point / p_daily_violin\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\nThe upper plot shows that as **Year 1** (green) went on, my time spent on PhD things slightly increased—makes sense, since I was wrapping up other lingering projects and turning my focus more and more to the PhD.\n**Year 2** (pink) shows a slight a drop-off over time.\nThen **Year 3** (blue) was pretty stable, and **Year 4** (orange) started with some vigorous experiment-running and thesis-writing, then decreased quickly as the PhD reached an end.\n\nThe violins in the lower plot aggregate the data for each year.\nThey show that in Years 1 and 2, I worked too long too often—I'm glad I got that impulse under control for Years 3 and 4.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhrs_daily |>\n  ungroup() |>\n  summarise(\n    mean_daily   = round(mean(daily_hrs), 1),\n    median_daily = round(median(daily_hrs), 1),\n    min_daily    = round(min(daily_hrs), 2),\n    max_daily    = round(max(daily_hrs), 1)\n  ) |>\n  knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n| mean_daily| median_daily| min_daily| max_daily|\n|----------:|------------:|---------:|---------:|\n|        5.2|          5.4|      0.08|      11.5|\n\n\n:::\n:::\n\n\n\n&nbsp;\n\nOverall, on average I spent 5.2 hours per day focused on PhD work.\nMy median work day was 5.4 hours.\nMy shortest work day was five minutes (lol), and my longest work day was 11.5 hours (bad. don't do this).\n\n\n# How many hours per task type?\n\nMy work fell into five broad categories:\n\n- **Admin:** Covers misc set-up and bureaucracy around the PhD, as well as my admin tasks within my research group.\n- **Community:** Covers reading groups, talk series, and conferences/workshops.\n- **Coursework:** Covers the required courses that were a condition of my funding as well as courses I audited for fun.\n- **Research:** Covers reading the literature, designing and implementing experiments and models, writing everything up, preparing talks, and the PhD examination process.\n- **Teaching:** Covers tutoring, guest lecturing, my one-on-one stats chats sessions, and working toward my AFHEA accreditation.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhrs |>\n  group_by(tasktype) |>\n  summarise(hrs = sum(mins)/60) |>\n  arrange(hrs) |>\n  mutate(tasktype = factor(tasktype, levels = tasktype)) %>% \n  ggplot(aes(y = tasktype, x = hrs, fill = tasktype)) +\n  geom_col() +\n  geom_text(\n    aes(\n      label = round(hrs), \n      x = hrs + (15 * log(hrs))  # scale the spacing by magnitude of hrs\n    ), family = 'Fira Sans') +\n  labs(\n    y = element_blank(),\n    x = 'Total hours'\n  ) +\n  theme(\n    axis.ticks.y = element_blank(),\n    legend.position = 'none'\n  ) +\n  scale_fill_manual(values = c(palette_tasktype[1], palette_tasktype[3], palette_tasktype[2], palette_tasktype[5], palette_tasktype[4]))+\n  NULL\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\nThis looks about right!\nLots and lots of research, plenty of teaching and community engagement, a bit of course work, with admin sitting blissfully in last place.\n\n\n# Task types over time\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhrs |>\n  group_by(month_idx, tasktype, year) |>\n  summarise(hrs = sum(mins)/60) |>\n  ggplot(aes(x = month_idx, y = hrs, fill = tasktype)) + \n  geom_bar(stat = 'identity', position = 'stack') +\n  scale_x_continuous(breaks = c(5, 17, 29, 41), labels = c(2022, 2023, 2024, 2025)) +\n  labs(\n    y = 'Hours/\\nmonth',\n    x = element_blank(),\n    fill = element_blank()\n  ) +\n  scale_fill_manual(values = palette_tasktype) +\n  NULL\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nI did a lot of tasks pretty regularly across the whole four years: regular admin, regular community engagement, regular research.\nThe big swaths of yellow coursework in the beginning were my required courses, and the for-fun auditing happened toward the end.\n\nThe big red spike of teaching in early 2023 is when I stepped in to design and run the last several weeks of a PG-level Bayesian stats course.\nThat was such a fun and formative experience—it's hard to believe that it was more than half a PhD ago.\n\n\n# How many hours per research project?\n\nI conducted four research projects during the PhD, and each project makes up one content chapter in my thesis.\n\n&nbsp;\n\n![A schematic illustrating the language acquisition phenomena I investigated in my thesis.](imgs/phd-chapters.png){width=60% fig-align=\"center\"}\n\n&nbsp;\n\nMy time on these projects was lumped together under the **Research** task type I plotted above, but of course I also recorded how much time I spent on each project individually.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmain_projs <- c('Word segmentation', 'Rule learning',  'Rule generalisation',  'Rule structure generalisation')\n\nhrs |>\n  filter(tasklabel %in% main_projs) |> \n  group_by(tasklabel) |>\n  summarise(hrs = sum(mins)/60) |>\n  arrange(hrs) |>\n  mutate(tasklabel = factor(tasklabel, levels = tasklabel)) |>\n  ggplot(aes(y = tasklabel, x = hrs, fill = tasklabel)) +\n  geom_col() +\n  geom_text(\n    aes(\n      label = round(hrs), \n      x = hrs + 30\n    ), family = 'Fira Sans') +\n  labs(\n    y = element_blank(),\n    x = 'Total hours'\n  ) +\n  theme(\n    axis.ticks.y = element_blank(),\n    legend.position = 'none'\n    ) +\n  scale_fill_manual(values = c(palette_proj[2], palette_proj[4], palette_proj[1], palette_proj[3])) +\n  NULL\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nI always knew that the **Rule generalisation** project (green, Chapter 4) was closest to my heart, but I'm still amused to see that I dedicated more than double as much time to it as to any of the others.\n\n\n# Research projects over time\n\nOne of the plots I was most curious to generate was this next one.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhrs |>\n  filter(tasklabel %in% main_projs) |>\n  group_by(month_idx, tasklabel, year) |>\n  summarise(hrs = sum(mins)/60) |>\n  mutate(tasklabel = factor(tasklabel, levels = main_projs)) |>\n  ggplot(aes(x = month_idx, y = hrs, fill = tasklabel)) + \n  geom_bar(stat = 'identity', position = 'stack') +\n  scale_x_continuous(\n    breaks = c(5, 17, 29, 41), \n    labels = c(2022, 2023, 2024, 2025),\n    ) +\n  scale_fill_manual(values = palette_proj) +\n  theme(\n    legend.position = 'bottom',\n    ) +\n  labs(\n    y = 'Hours/\\nmonth',\n    x = element_blank(),\n    fill = element_blank(),\n  ) +\n  guides(\n    fill=guide_legend(nrow=2),\n    ) +\n  NULL\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\nThe **Word segmentation** project (red, Chapter 2) was my first-year project, and it grew up to become [Pankratz et al., (2024)](https://onlinelibrary.wiley.com/doi/10.1111/cogs.13429).\nFor this project, I ran one experiment in July 2022.\nThe manuscript was submitted in late 2022, and the splashes of red in 2023 were the revisions following peer review.\nThen in early 2024 came the final formatting checks, and then the paper was out!\n\nThe **Rule learning** project (yellow, Chapter 3), which I did together with [Aislinn Keogh](https://aislinnkeogh.github.io), is the longest-running project of the four.\nWe ran two experiments, one in April 2023 and one almost a year later in March 2024.\nThis project never got published, but it appears as a chapter in each of our PhD theses.\n\nThe **Rule generalisation** project (green, Chapter 4) consumed my time and my thinking for much of 2023 and well into 2024.\nI consider it the heart of my PhD—it's the project I find the most interesting and the most compelling.\nWhich explains why I spent 661 hours on it!\nThe project did have some false starts, though.\nI ran one experiment for it in October 2022, but that experiment never saw the light of day because of confounds in the design that I detected too late.\nA second experiment, the one that actually appears in the thesis, was run in July 2023.\n\nFinally, the **Rule structure generalisation** project (blue, Chapter 5) was my main focus in my final year.\nFor this project, I ran four experiments within three months: one in June 2024, two in August, and one in September.\nThose four experiments were all pretty similar, but still, four experiments in three months is serious progress, considering I spent my entire first year on one single experiment!\nTurns out a PhD does actually teach you things.\nWho knew?\n\n\n# Thesis writing and viva prep\n\nIn addition to the four content chapters, my thesis contains an introduction chapter, a general discussion chapter, and a bunch of appendices.\nThe time I spent planning, writing, and revising that thesis-specific material was recorded as **Thesis** time.\n**Thesis** time also contains hours spent on LaTeX tomfoolery and on implementing the minor corrections after my viva.\n\nUnder **Viva** time, I counted the hours I spent designing my pre-viva talk (which is probably my favourite talk I've ever given) as well as doing more traditional prep for the viva itself.\nHere I'll plug Nathan Ryder's [Viva Survivors](http://viva-survivors.com) web site and workshop, and especially the [7776 Mini-Vivas resource](http://viva-survivors.com/2018/11/new-resource-7776-mini-vivas/).\nDoing a mock viva using that resource was the most useful part of my prep by a mile.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhrs |>\n  filter(tasklabel %in% c('Thesis', 'Viva')) |>\n  group_by(tasklabel) |>\n  summarise(hrs = round(sum(mins)/60)) |>\n  knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n|tasklabel | hrs|\n|:---------|---:|\n|Thesis    | 235|\n|Viva      |  55|\n\n\n:::\n:::\n\n\n&nbsp;\n\nAll in all, I spent 235 hours on thesis-specific tasks and 55 hours creating the pre-viva talk and preparing for the viva itself.\n\nHere's how those hours played out over time:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhrs |>\n  filter(tasklabel %in% c('Thesis', 'Viva')) |>\n  group_by(week_idx, tasklabel, year) |>\n  summarise(hrs = sum(mins)/60) |>\n  ggplot(aes(x = week_idx, y = hrs, fill = tasklabel)) + \n  geom_vline(xintercept = 175, colour = palette_exam[1], linetype = 'dashed') +\n  geom_text(x = 175.5, y = 35, label = 'Thesis submitted on 6 Jan 2025', hjust = 0, family = 'Fira Sans', colour = palette_exam[1]) + \n  geom_vline(xintercept = 180, colour = palette_exam[2], linetype = 'dashed') +\n  geom_text(x = 180.5, y = 30, label = 'Viva on 11 Feb 2025', hjust = 0, family = 'Fira Sans', colour = palette_exam[2]) +\n  geom_bar(stat = 'identity', position = 'stack') +\n  scale_x_continuous(\n    breaks = c(153, 157, 161, 165, 170, 174, 179, 183, 187),\n    labels = c('Aug 2024', 'Sep', 'Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar', 'Apr 2025'),\n    limits = c(152, 189)\n    ) +\n  scale_fill_manual(values = palette_exam) +\n  scale_colour_manual(values = palette_exam) +\n  theme(\n    legend.position = 'bottom',\n  ) +\n  labs(\n    y = 'Hours/\\nweek',\n    x = element_blank(),\n    fill = element_blank(),\n  ) +\n  NULL\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\nI spent most of November and December writing.\nAfter a week off during the holidays, the thesis was ready to submit by early January, and then I turned immediately to preparing for the viva in mid-February.\n\nFollowing the viva, I took a month to prepare for a job interview, and then in April I picked up the thesis again and worked on my corrections for two relaxed weeks.\nThose corrections were submitted on 9 April and approved on 15 April, and now, 242,516 minutes later, I can call myself Doctor 😊\n\n\n# Epilogue: Citation frequencies\n\nAs a cherry on top, I wanted to look at how often I cited each piece of literature.\nEach citation is itemised in the `.bcf` file produced by biblatex.\nAnd, surprise surprise, Zipf appears both in name and in rank/frequency law:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbcf <- xml2::read_xml('data/output.bcf')\ncitekeys <- xml2::xml_text(xml2::xml_find_all(bcf, \".//bcf:citekey\"))\nrefs_freqdist <- as.data.frame(table(citekeys)) %>% \n  arrange(Freq) %>% \n  mutate(citekeys = factor(citekeys, levels = citekeys))\n\nrefs_freqdist %>% \n  ggplot(aes(x = Freq, y = citekeys)) +\n  geom_bar(stat = 'identity') +\n  labs(\n    y = element_blank(),\n    x = 'Frequency'\n    ) +\n  theme(axis.text.y = element_text(size=6)) +\n  scale_x_continuous(position = 'top') +\n  NULL\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n\n(Zipf, 1949 shows up in Rank 49 with a frequency of 5.)\n\nAppropriately, considering my PhD was about how distributional statistics affect language learning, my top five sources are:\n\n1. Saffran, J. R., Aslin, R. N., & Newport, E. L. (1996). Statistical learning by 8-month-old infants. *Science*, 274(5294), 1926–1928. <https://doi.org/10.1126/science.274.5294.1926>\n\n2.  Saffran, J. R., Newport, E. L., & Aslin, R. N. (1996). Word segmentation: The role of distributional cues. *Journal of Memory and Language*, 35(4), 606–621. <https://doi.org/10.1006/jmla.1996.0032>\n\n3. Misyak, J. B., Christiansen, M. H., & Tomblin, J. B. (2010). On-line individual differences in statistical learning predict language processing. *Frontiers in Psychology*, 1. <https://doi.org/10.3389/fpsyg.2010.00031>\n\n4. Baayen, R. H. (2001). *Word frequency distributions*. Kluwer Academic Publishers.\n\n5. Frost, R. L. A., & Monaghan, P. (2016). Simultaneous segmentation and generalisation of non-adjacent dependencies from continuous speech. *Cognition*, 147, 70–74. <https://doi.org/10.1016/j.cognition.2015.11.010>\n\n\nMany processes lead to Zipfian distributions, indeed...\n\n\n# Session info\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.4.3 (2025-02-28)\nPlatform: aarch64-apple-darwin20\nRunning under: macOS Sequoia 15.4\n\nMatrix products: default\nBLAS:   /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRblas.0.dylib \nLAPACK: /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.0\n\nlocale:\n[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8\n\ntime zone: Europe/London\ntzcode source: internal\n\nattached base packages:\n[1] stats     graphics  grDevices datasets  utils     methods   base     \n\nother attached packages:\n [1] patchwork_1.3.0 lubridate_1.9.4 forcats_1.0.0   stringr_1.5.1  \n [5] dplyr_1.1.4     purrr_1.0.4     readr_2.1.5     tidyr_1.3.1    \n [9] tibble_3.2.1    ggplot2_3.5.2   tidyverse_2.0.0\n\nloaded via a namespace (and not attached):\n [1] generics_0.1.3    renv_1.0.5        xml2_1.3.8        stringi_1.8.7    \n [5] lattice_0.22-6    hms_1.1.3         digest_0.6.37     magrittr_2.0.3   \n [9] evaluate_1.0.3    grid_4.4.3        timechange_0.3.0  fastmap_1.2.0    \n[13] Matrix_1.7-2      jsonlite_2.0.0    mgcv_1.9-1        scales_1.3.0     \n[17] cli_3.6.4         rlang_1.1.6       crayon_1.5.3      bit64_4.6.0-1    \n[21] munsell_0.5.1     splines_4.4.3     withr_3.0.2       yaml_2.3.10      \n[25] tools_4.4.3       parallel_4.4.3    tzdb_0.5.0        colorspace_2.1-1 \n[29] vctrs_0.6.5       R6_2.6.1          lifecycle_1.0.4   bit_4.6.0        \n[33] vroom_1.6.5       pkgconfig_2.0.3   pillar_1.10.2     gtable_0.3.6     \n[37] glue_1.8.0        xfun_0.52         tidyselect_1.2.1  rstudioapi_0.17.1\n[41] knitr_1.50        farver_2.1.2      htmltools_0.5.8.1 nlme_3.1-167     \n[45] labeling_0.4.3    rmarkdown_2.29    compiler_4.4.3   \n```\n\n\n:::\n:::\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}