{
  "hash": "5525db518ed1aa3c5d78dbc8fee5a20a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Power analysis with `mixedpower` for linear mixed models (workshop materials)\"\ndate: \"2026-03-13\"\ncategories: [Stats, Resources]\nimage: \"index_files/figure-html/unnamed-chunk-25-1.png\"\ntoc: true\nformat:\n  html:\n    code-fold: show\n    code-tools: true\n---\n\nThis post covers the power analysis workshop I'm running in Prof. Holly Branigan and Prof. Martin Pickering's lab meeting on 17 March, 2026.\n\nThe models we'll look at:\n\n- [Example 1](#ex1): `logRT ~ wdFreq + (wdFreq | ppt_id)`\n- [Example 2](#ex2): `logRT ~ wdFreq * bigramFreq + (wdFreq * bigramFreq | ppt_id) + (1 | wd_id)`\n\n\n::: {.cell}\n<style type=\"text/css\">\ndiv.yellow{ \n    border-radius: 5px; \n    padding: 20px 20px 10px 20px; \n    margin-top: 20px; \n    margin-bottom: 20px; \n    background-color:#FFFBEE !important; \n}\n</style>\n:::\n\n\n# Get set up in R\n\nLoad the libraries this workshop will use:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(simr)\nlibrary(mixedpower)\n```\n:::\n\n\n\n\n\n\nIf you don't have `mixedpower` installed already, you can get it with the following code.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif(!require(\"devtools\")){\n  install.packages(\"devtools\", dependencies = TRUE)\n}\ndevtools::install_github(\"DejanDraschkow/mixedpower\")\n```\n:::\n\n\n(`mixedpower` lives on GitHub, not CRAN, so the usual `install.packages()` won't work.)\n\n\n# Build intuitions\n\n## Why do we care about power?\n\nShort answer: power analyses are useful because they tell us how many experimental participants we should try to recruit.\n\n:::yellow\n🧠✨ \nWhy do you care? Why were you interested in having this workshop?\n:::\n\n\n## What is statistical power?\n\nFor any null hypothesis (H0) that we are trying to test, there are **two possible true states of the world:**\n\n1. In reality, the H0 is true.\n1. In reality, the H0 is false.\n\nAssuming we're doing Null Hypothesis Significance Testing, aka NHST, then ideally, these true states of the world would map exactly to the **two possible outcomes of a statistical test:**\n\n1. We fail to reject the H0.\n1. We reject the H0.\n\nHowever, even if the H0 is really truly false, we are (alas!) not guaranteed to reject it.\n\nIn other words, **the probability that our test will correctly reject the H0** (that is, that we'll reject the H0 when it really truly is false) is likely going to be less than 100%.\nWhatever that probability actually is is our test's **\"statistical power\".**\n\n:::{.callout-tip collapse = 'true'}\n#### How decisions about H0 map to truth of H0\n\n![](imgs/2x2.png){fig-align=\"center\"}\n\n:::\n\n\nStatistical power depends on three values:\n\n1. our accepted alpha level (aka our false positive rate, aka our Type I error rate, aka the probability of rejecting the H0 when it is actually true);\n1. the true size of the effect out there in reality; and\n1. the number of observations we have gathered.\n\n**On alpha:** \nThe smaller your alpha, the lower your statistical power, because rejecting the H0 becomes more difficult.\nIn Psychology and sister disciplines, we usually set our alpha at 5%.\nThis means that we accept the risk that we'll be incorrectly rejecting the H0 5% of the time.\n\n**On true effect size:** \nThe larger the true effect size, the more likely a test is to correctly detect it.\nOf course, we don't know the true effect size—that's why we're doing stats about it!\nBut we can use previous research and our expert judgements to make some educated guesses about what kinds of true effect sizes would be reasonable and/or theoretically interesting.\n\n**On number of observations:** The larger your sample, the higher your power. \nThe goal of the power analysis is usually to discover how many participants we need for a reasonably-powered study (which we usually say is 80% power).\nWe'll figure out how many participants we need by simulating a bunch of different sample sizes and looking at the power of each scenario.\n\n\n\n## Simulation, you say?\n\n<!-- Yes—we do a priori power analyses (that is, power analyses before the main study is run) by simulating data that contains the effect we are interested in, then fitting a model to that data, and checking whether we  -->\n\nThis schematic shows the basic logic behind a simulation-based power analysis:\n\n![](imgs/sim-schematic.png){fig-align=\"center\"}\n\n\n\n## When to run a power analysis?\n\nThe best time to run a power analysis is **after piloting your experiment** and **before running the main thing.**\nYou'll hear this referred to as an \"a priori power analysis\".\n\n**Why run the pilot first?**\nBecause pilot data helps us approximate average outcomes as well as how much variability we should expect from which sources.\nFor example, the pilot will give us the best possible information about how much\n\n- by-participant variability\n- by-stimulus variability\n- by-whatever-else variability\n- residual variability\n\nour actual experimental data will contain.\n\n**Why not run the experiment first and analyse its power after the fact?**\nBecause if you use your observed effect size as a stand-in for the true effect size, then you'll just end up with a different way of formulating whatever p-value you observed.\nSo a post-hoc power analysis doesn't actually offer any new information.\n(For more detail, see [this blog post by Daniel Lakens](https://daniellakens.blogspot.com/2014/12/observed-power-and-what-to-do-if-your.html).)\n\n\n\n# Ex. 1: Start simple(ish) 🌶️ {#ex1}\n\nImagine you're running a lexical decision task to analyse the effect of a word's frequency on how quickly people identify it as a word in their language.\n\n:::yellow\n🧠✨  What kind of effect would you expect to find?\n:::\n\nBecause many of you said you work with continuous outcomes, our outcome variable will be logged reaction times.\nBut the same principles apply even if you have a different kind of outcome variable and different model family, e.g., 0/1 data and a binomial family.\n\nAnd because many of you said you work with categorical predictors, we'll group words into two frequency classes: one for low-frequency words, one for high-frequency words.\n(But [Example 2 below](#ex.-2-get-spicier) will also throw in a continuous z-scored predictor.)\n\n\nAll told, our variables for this analysis will be the following:\n\n- `logRT`: logged reaction times (smaller values = faster)\n- `wdFreq`: categorical, with two levels: `low`, `high`; varies within participants \n- `ppt_id`: categorical, with one value per participant\n\n\n## Build up basic power analysis, step by step\n\nHere are the steps we're going to follow:\n\n1. Formulate the model you want to fit.\n1. Define how all variables are coded/transformed.\n1. Simulate design matrix (aka a big dataframe of all the observed combinations of our variables, not including the outcome).\n1. Define parameter values (i.e., the intercept, the variance components, and the true effect size(s) we're interested in simulating).\n1. Use all this information to set up a simulation model with `simr::makeLmer()`.\n1. Use that model to run the power analysis with `mixedpower::mixedpower()`.\n\n(In the later examples, we'll iterate over a handful of different true effect sizes, to see how the true effect size makes a difference for how many participants we'd need to recruit.\nThat iteration will bundle steps 5 and 6 together into one.)\n\n\n### 1. Formulate the model you want to fit\n\nWe'll get the most conservative power estimates if the model we use for the power analysis is the maximal model that your data structure permits.\n(For more detail on this point, see the [Questions you submitted](#questions-you-submitted) section below.)\n\nHere is the model formula in R syntax:\n\n`logRT ~ wdFreq + (wdFreq | ppt_id)`\n\n\nIf you want to see a mathematical version of this model specification, then you can uncollapse the box below.\nSome people find the mathematical specification useful because it specifies all the parameters that we're going to need to define in the next few steps.\nBut if that doesn't spark joy, then don't worry about it!\n\n:::{.callout-tip collapse = 'true'}\n#### For the keen: Mathematical model specification\n\n**In words:**\n\n- Each participant $i$'s log RT equals\n  - the intercept $\\beta_0$ plus each participant's intercept adjustment $u_{0i}$; plus\n  - the slope over `wdFreq` $\\beta_1$ plus each participant's slope adjustment $u_{1i}$, all times `wdFreq`; plus\n  - some error $\\epsilon$.\n- The error $\\epsilon$ is sampled from a Normal distribution with mean 0 and standard deviation (SD) $\\sigma$.\n- Each participant's adjustments to intercept $u_{0i}$ and slope $u_{1i}$ are sampled together from a bivariate Normal distribution.\n  - The mean of each dimension is 0.\n  - The spread of the distribution in each dimension is defined by a variance-covariance matrix with the variance (SD$^2$) of each adjustment on the diagonal and the correlations between those adjustments on the off-diagonals. Here the correlations are assumed to be zero.\n  - NB: Because slope and intercept adjustments are uncorrelated in this example, I could also have written them being drawn from two separate univariate Normals, like in the $\\epsilon$ line. \n  However, the `simr` code below wants a variance-covariance matrix, even if the correlations are 0, so for consistency, I'm using the bivariate Normal version here to give a reference point for where the `simr` variance-covariance matrix comes from.\n  \n\n**In math:**\n\n$$\n\\begin{align}\n\\text{logRT}_i &= (\\beta_0 + u_{0i}) + (\\beta_1 + u_{1i}) \\cdot \\text{wdFreq} + \\epsilon \\\\\n\\epsilon &\\sim \\text{Normal}(0, \\sigma) \\\\\n\\pmatrix{u_{0i} \\\\ u_{1i}} &\\sim \\text{Normal}\n\\begin{bmatrix}\n\\pmatrix{0 \\\\ 0},\n\\pmatrix{\\sigma_{u_{0i}}^2 & 0 \\\\ 0 & \\sigma_{u_{1i}}^2}\n\\end{bmatrix}\n\\\\\n\\end{align}\n$$\n\n\n**Parameter glossary:**\n\n- $i$ indexes participants\n- $\\beta_0$ is the fixed intercept\n- $u_{0i}$ is the by-participant adjustment to fixed intercept\n- $\\beta_1$ is the fixed slope over `wdFreq`\n- $u_{1i}$ is the by-participant adjustment to fixed slope\n- $\\epsilon$ is the error\n- $\\sigma$ is the SD of errors\n- $\\sigma_{u_{0i}}$ is the SD of by-participant intercept adjustment\n- $\\sigma_{u_{1i}}$ is the SD of by-participant slope adjustment\n\n:::\n\n### 2. Define how all variables are coded/transformed\n\nIn order to make a reasonable guess about what values the model parameters might have, we need to know about the kinds of numbers that represent each variable.\n\n- What units/scales do continuous predictors use?\n- What contrast coding schemes do categorical predictors use?\n\nWe already know that the outcome `logRT` is in **log units,** not ms.\n(Logging RTs is important so that residuals are approximately normally distributed.)\n\nLet's say that `wdFreq` will be \"sum-coded\", which you'll also see called \"effect-coded\", which you'll also see called \"deviation-coded\".\nBecause these words have no meaning anymore, let's just be explicit and say that **`low` will be coded as –0.5 and `high` as +0.5.**\n\nConsequently:\n\n- The intercept will represent the **grand mean log RT.**\n  - What's a grand mean? Take the mean log RT of `low` frequency words and the mean log RT of `high` frequency words; the mean of both of those means is the grand mean.\n- The slope over `wdFreq` will represent the **change in log RT as we move from `low` to `high`.**\n\n:::yellow\n🧠✨ \nDo you think that the `wdFreq` coefficient should have a positive value or a negative value?\n:::\n\n\n### 3. Simulate design matrix\n\nImagine running a pilot study in which you gather logRT data from ten different participants.\nIn your design, each participant sees ten words in total: five words from the `low` frequency group of `wdFreq` and five words from the `high` frequency group of `wdFreq`.\nAfter data collection, you'd end up with a dataframe with the following structure:\n\n- a column `ppt_id` containing each participant ID repeated ten times, once per word.\n- a column `wdFreq` containing (for each participant) –0.5 repeated five times for the five `low` frequency words, +0.5 repeated five times for the five `high` frequency words; and\n- a column `logRT` containing each participant's log reaction time for the given trial.\n\nIn this step, we're basically going to generate all columns of this dataframe *except* for the outcome variable (which here is `logRT`).\nIn stats terms, we're generating the \"design matrix\".\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_ppts        <- 10  # how many participants to simulate?\n                     # (this number should match your pilot)\n\nn_wds_per_ppt <- 10  # how many words does each ppt see?\n                     # (this number should match your pilot + experiment)\n\nsimdat1 <- tibble(\n  ppt_id = rep(1:n_ppts, each = n_wds_per_ppt),\n  wdFreq = rep(\n    c(\n      rep(-0.5, n_wds_per_ppt/2), \n      rep(0.5, n_wds_per_ppt/2)\n    ), n_ppts\n  )\n)\n\nsimdat1 |> head(20)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 20 × 2\n   ppt_id wdFreq\n    <int>  <dbl>\n 1      1   -0.5\n 2      1   -0.5\n 3      1   -0.5\n 4      1   -0.5\n 5      1   -0.5\n 6      1    0.5\n 7      1    0.5\n 8      1    0.5\n 9      1    0.5\n10      1    0.5\n11      2   -0.5\n12      2   -0.5\n13      2   -0.5\n14      2   -0.5\n15      2   -0.5\n16      2    0.5\n17      2    0.5\n18      2    0.5\n19      2    0.5\n20      2    0.5\n```\n\n\n:::\n:::\n\n\n<!-- There are [so many R packages out there](https://www.scienceverse.org/faux/#other-simulation-packages) that will help you simulate data. -->\n\n(There are [so many different ways](https://www.scienceverse.org/faux/#other-simulation-packages) to generate this kind of data in R.\nI leave coding different experimental designs as a challenge for the reader 😊)\n\n\n### 4. Define parameter values\n\nWe want our power analysis to use our best guesses about the true values of all the model's parameters.\nSo, here's where we use pilot data to make our best guess about (i) the model's intercept and (ii) the variability we might expect to see in the data.\n\nWe will also use our expert judgement to define (iii) the smallest effect size that we'd consider theoretically interesting—a key step of the power analysis!\n\n\n#### (i) Intercept\n\nBecause our predictor is coded with $\\pm$ 0.5 (i.e., it is centered on zero), the model's intercept represents the grand mean log RT.\n\n\nImagine we observed the following (unrealistically lovely and round) estimate from our pilot data:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrand_mean <- 6.5\n```\n:::\n\n\nFor reference, 6.5 log units maps to\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexp(6.5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 665.1416\n```\n\n\n:::\n:::\n\n\nmilliseconds.\n\n\n#### (ii) Variance components\n\nOur model, `logRT ~ wdFreq + (wdFreq | ppt_id)`, is modelling three sources of variability:\n\n- by-participant adjustments to the intercept;\n- by-participant adjustments to the slope; and\n- residual error.\n\nFor the power analysis, we need to define how variable we expect each of these three parameters to be.\nSpecifically, we need to give the standard deviation (SD) of each one.\n\nLet's imagine that a pilot study gave us the following (unrealistically lovely and round) values:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsd_int_by_ppt <- 1\nsd_slp_by_ppt <- 0.5\nsd_resid      <- 0.5\n```\n:::\n\n\n\n\n#### (iii) Effect of interest\n\nOur research question asks how differences in `wdFreq` are associated with differences in `logRT`.\nSo the parameter whose significance we are testing is the coefficient estimated for `wdFreq`.\n\n:::yellow\n🧠✨ \nImagine we find a difference between low-frequency and high-frequency words of 0.001 log units.\nIn other words, **an effect size of 0.001 log units.**\n\nEven if we were able to reject the H0 that this parameter is equal to zero, is a difference of that magnitude **theoretically interesting?**\n\nWhat about:\n\n- 0.01 log units?\n- 0.1 log units?\n- 1 log unit?\n- 10 log units?\n- 100 log units?\n:::\n\n\n:::{.callout-tip collapse = 'true'}\n#### Translating effect sizes between log units and ms\n\nThe log transformation is non-linear, **so an effect size in log units will translate to different effect sizes in ms**, depending on the original values we're comparing.\n\nFor example, imagine an effect size of 1 log unit.\n\nIf that effect size is the difference between 3 log units and 4 log units, then it maps to a difference in RT in ms of:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexp(4) - exp(3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 34.51261\n```\n\n\n:::\n:::\n\n\nBut if that same one-unit effect size is the difference between 5 log units and 6 log units, then suddenly it maps to a difference in RT in ms of:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexp(6) - exp(5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 255.0156\n```\n\n\n:::\n:::\n\n\n\nHere is a visualisation of how the same difference between log units can map to very different differences on the ms scale:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\ntibble(\n  RT    = seq(0:450),\n  logRT = log(RT)\n) |>\n  ggplot(aes(x = RT, y = logRT)) +\n  scale_y_continuous(breaks = 0:8, expand = c(0, 0)) +\n  scale_x_continuous(expand = c(0, 0)) +\n  labs(x = 'RT (ms)', y = 'log RT (log units)') +\n  # horiz green\n  geom_segment(x = 0, y = 3, xend = exp(3), yend = 3, colour = '#2B8654') +\n  geom_segment(x = 0, y = 4, xend = exp(4), yend = 4, colour = '#2B8654') +\n  geom_text(\n    x = 5,\n    y = 4-.2,\n    colour = '#2B8654', \n    family = 'Fira Sans',\n    label = paste0('diff: 1'),\n    hjust = 0\n  ) +\n  # vert green\n  geom_segment(x = exp(3), y = 0, xend = exp(3), yend = 3, colour = '#2B8654') +\n  geom_segment(x = exp(4), y = 0, xend = exp(4), yend = 4, colour = '#2B8654') +\n  geom_text(\n    x = exp(3) + (exp(4)-exp(3))/2, \n    y = 1,\n    colour = '#2B8654', \n    family = 'Fira Sans',\n    label = paste0('diff:\\n ', round(exp(4) - exp(3)), 'ms')\n  ) +\n  # horiz pink\n  geom_segment(x = 0, y = 5, xend = exp(5), yend = 5, colour = '#FF6393') +\n  geom_segment(x = 0, y = 6, xend = exp(6), yend = 6, colour = '#FF6393') +\n  geom_text(\n    x = 5,\n    y = 6-.2,\n    colour = '#FF6393', \n    family = 'Fira Sans',\n    label = paste0('diff: 1'),\n    hjust = 0\n  ) +\n  # vert pink\n  geom_segment(x = exp(5), y = 0, xend = exp(5), yend = 5, colour = '#FF6D9A') +\n  geom_segment(x = exp(6), y = 0, xend = exp(6), yend = 6, colour = '#FF6D9A') +\n  geom_text(\n    x = exp(5) + (exp(6)-exp(5))/2, \n    y = 1,\n    colour = '#FF6D9A', \n    family = 'Fira Sans',\n    label = paste0('diff: ', round(exp(6) - exp(5)), 'ms')\n  ) +\n  geom_point() +\n  NULL\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\nSo, given that effect sizes in log units can translate to so many different effect sizes in ms, **how do we know what effect sizes in log units are reasonable?**\n\n- Good: Look at previous literature.\n- Better: Use your pilot data to estimate what magnitude of values you're comparing.\n\n:::\n\n\nHere's where we use our expert judgement, along with results from prior literature, to decide on the *smallest* effect size that would be theoretically interesting.\nThis value is often abbreviated as SESOI, for \"Smallest Effect Size Of Interest\".\n\nLet's imagine for now that our SESOI is a change of 0.2 log units.\nWe'll represent this value as negative, because we expect log RT to get smaller (i.e., faster) when we move from low-frequency words (coded as –0.5) to high-frequency words (coded as +0.5).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsesoi <- -0.2\n```\n:::\n\n\nThe power analysis that follows assumes that the true effect out there in reality is –0.2 log units.\n**This is how we know the H0 in our simulation is false: we've declared that it is false, because we have given this parameter a value different from zero.**\n\n\n([Later on](#iterate-over-different-effect-sizes) we will also check a couple other possible true effect sizes, both smaller and larger, so that we understand the power properties of our design more completely.)\n\n\n### 5. Set up simulation model with `makeLmer()`\n\nIn Step 6 below, we'll use `mixedpower()` to actually run the power analysis proper.\nOne of the inputs that `mixedpower()` wants is a linear model fit to some data.\n\nWe haven't simulated any outcome data—we've just defined a design matrix and some parameter values.\nAnd that is fine!\nWe can use `simr`'s function `makeLmer()` to create a model object using all this information we've specified above.\nWith `simr` in our back pocket, we don't actually need to simulate any log RTs ourselves 😊\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsimmod1 <- makeLmer(\n  formula = logRT ~ wdFreq + (1 + wdFreq | ppt_id),\n  \n  ## fixed effect coefs: intercept, wdFreq slope\n  fixef = c(grand_mean, sesoi),\n  \n  ## residual SD\n  sigma = sd_resid,\n  \n  ## variance-covariance matrix for random effects\n  VarCorr = matrix(\n    c(sd_int_by_ppt^2, 0, 0, sd_slp_by_ppt^2),\n    nrow=2,\n    byrow = T),\n  \n  ## design matrix\n  data = simdat1\n)\n\nsummary(simmod1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML ['lmerMod']\nFormula: logRT ~ wdFreq + (1 + wdFreq | ppt_id)\n   Data: simdat1\n\nREML criterion at convergence: 177.1\n\nScaled residuals: \n     Min       1Q   Median       3Q      Max \n-2.23784 -0.51832  0.01271  0.55594  2.08886 \n\nRandom effects:\n Groups   Name        Variance Std.Dev. Corr\n ppt_id   (Intercept) 1.00     1.0          \n          wdFreq      0.25     0.5      0.00\n Residual             0.25     0.5          \nNumber of obs: 100, groups:  ppt_id, 10\n\nFixed effects:\n            Estimate Std. Error t value\n(Intercept)   6.5000     0.3202  20.303\nwdFreq       -0.2000     0.1871  -1.069\n\nCorrelation of Fixed Effects:\n       (Intr)\nwdFreq 0.000 \n```\n\n\n:::\n:::\n\n\n(Make sure all the numbers you defined are showing up where you expected them to be!)\n\n\n### 6. Run power analysis with `mixedpower()`\n\nAll that's left is to decide how many different participants counts we want to simulate.\nIt's good to range from \"absolutely utopian in the year 1985\" to \"we do not have this much money\".\nIf counts are unrealistic at both extremes, then all our bases are covered:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_ppts_to_sim <- c(40, 60, 80, 100, 120)\n```\n:::\n\n\n\n**And now we run the power analysis!**\n\n- Remember that our H0 is that the association between `wdFreq` and `logRT` is zero.\n- We know that the H0 is false, because we defined the association between `wdFreq` and `logRT` to be not zero, but rather –0.2 log units.\n- So, given that the H0 is false, how often does our design correctly reject the H0 with different numbers of participants? \n**In other words, what is our design's power at different participant counts?**\n\nLet's find out:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npower1 <- mixedpower(\n  model = simmod1, \n  data = simdat1,\n  fixed_effects = c(\"wdFreq\"),\n  simvar = \"ppt_id\",\n  steps = n_ppts_to_sim,\n  critical_value = 2, \n  n_sim = 1000\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npower1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          40    60    80   100   120      mode effect\nwdFreq 0.557 0.729 0.848 0.918 0.966 databased wdFreq\n```\n\n\n:::\n:::\n\n\n- With 40 participants, power is 55.7%.\n- With 60 participants, power is 72.9%.\n- With 80 participants, power is 84.8%.\n- With 100 participants, power is 91.8%.\n- With 120 participants, power is 96.6%.\n\n:::yellow\n🧠✨ \nHow many participants would you aim to recruit?\n:::\n\n\n:::{.callout-tip collapse = 'true'}\n#### R tips for `mixedpower()`\n\n- ⌛️ It can take several seconds, even minutes, for these simulations to run, especially when iterating over different parameter values like we will below.\n- 🎲 Expect some slightly different values from mine. Usually I'd set a seed for a probabilistic process like this, but setting the seed seems to have no effect on `mixedpower()`, so results will be a little different every time 🙃\n- 🗃️  For the sake of internal reproducibility at least, if you're using R markdown, write `cache = T` in the header of the code chunk containing the call to `mixedpower()`. \nWith `cache = T`, the code chunk's output will be stored, so that the code doesn't need to be re-run every time you render the document.\n- 🖨️ While it's running, `mixedpower()` prints out a ton of status updates.\nTo suppress these in the rendered document, update the code chunk's header to also include `results = 'hide'`.\n\n:::\n\n\n## Iterate over different effect sizes\n\nTo understand our design's power properties, it's usually useful in practice to simulate a few different effect sizes, not just the SESOI.\nHere we'll look at values on either side of our SESOI.\n\n\n::: {.cell}\n\n```{.r .cell-code}\neffects_to_sim <- c(-0.1, -0.2, -0.5)\n```\n:::\n\n\n\nOne way to code this is to use a for loop (R superbrains, avert your eyes).\n\nThe code below takes Steps 5 and 6 and runs them three times.\nEach time, the `makeLmer()` model defines a different true effect size based on the `effects_to_sim` we defined above.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# set up accumulator to save the data from each iteration\n# (we'll add on a new row each time)\npower_accumulator1 <- tibble(\n '40' = NA, \n '60' = NA, \n '80' = NA, \n '100' = NA, \n '120' = NA,\n 'mode' = NA,\n 'effect' = NA,\n 'true_effect_size' = NA,\n)[0,]\n\n# iterate!\nfor(curr_effect in effects_to_sim){\n  \n  # set up the model with the current param estims \n  curr_model <- makeLmer(\n    formula = logRT ~ wdFreq + (1 + wdFreq | ppt_id),\n    fixef = c(grand_mean, curr_effect),\n    sigma = sd_resid,\n    VarCorr = matrix(\n      c(sd_int_by_ppt^2, 0, 0, sd_slp_by_ppt^2),\n      nrow = 2, \n      byrow = T\n    ),\n    data = simdat1\n  )\n  \n  # get power estims\n  curr_power <- mixedpower(\n    model = curr_model, \n    data = simdat1,\n    fixed_effects = c(\"wdFreq\"),\n    simvar = \"ppt_id\", \n    steps = n_ppts_to_sim,\n    critical_value = 2, \n    n_sim = 1000,\n  )\n  \n  # add current iteration's parameters to df\n  curr_power$true_effect_size  <- curr_effect\n  \n  # add to accumulator\n  power_accumulator1 <- rbind(power_accumulator1, curr_power)\n  \n}\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npower_accumulator1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           40    60    80   100   120      mode effect true_effect_size\nwdFreq  0.177 0.268 0.312 0.368 0.439 databased wdFreq             -0.1\nwdFreq1 0.572 0.716 0.841 0.915 0.961 databased wdFreq             -0.2\nwdFreq2 1.000 1.000 1.000 1.000 1.000 databased wdFreq             -0.5\n```\n\n\n:::\n:::\n\n\n\nAfter wrangling this data a bit, we can also make a nice little plot that shows power curves for our three different effect sizes:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npower_accumulator1 |>\n  \n  # make df tall, not wide\n  pivot_longer(\n    cols = as.character(n_ppts_to_sim),\n    names_to = 'n_ppts',\n    values_to = 'power'\n  ) |>\n  \n  # make things into factors so they plot nicely\n  mutate(\n    true_effect_size = factor(true_effect_size, levels = effects_to_sim),\n    n_ppts = factor(n_ppts, levels = n_ppts_to_sim)\n  ) |>\n  \n  # plot!\n  ggplot(aes(x = n_ppts, y = power, colour = true_effect_size)) +\n  geom_hline(yintercept = 0.8, linetype = 'dotted') +\n  geom_point() +\n  geom_line(aes(group = true_effect_size)) +\n  ylim(0, 1) +\n  labs(\n    y = 'Power (% times H0 correctly rejected)',\n    x = 'How many participants?',\n    colour = 'True effect size'\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-17-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n\n\n:::yellow\n🧠✨ \nImagine the true effect size is –0.1.\nHow many participants would you aim to recruit?\n:::\n\nAnd that's a power analysis!\n\n<br>\n\n# Ex. 2: Get spicier 🌶🌶 {#ex2}\n\nUsually our linear models are more complex than the model in Example 1.\nWe often want to model interactions between predictors, and we often have to account for variability from multiple sources (e.g., participant-level and stimulus-level).\nThis section illustrates the same process shown above for a more complex model.\n\nImagine we're still looking at log RTs in a lexical decision task.\nWe still have our categorical predictor `wdFreq`, but now we'll also incorporate the mean frequency of individual *bigrams* within each word.\nSo, we're adding in a continuous predictor, `bigramFreq`, and we'll also allow it to interact with `wdFreq`.\n\nOur variables for this analysis will be the following:\n\n- `logRT`: logged reaction times (smaller values = faster)\n- `wdFreq`: categorical, with two levels: `low`, `high`\n  - varies within participants\n  - varies between words\n- `bigramFreq`: continuous, mean bigram frequency within each word, z-scored\n  - varies within participants\n  - varies between words\n- `ppt_id`: categorical, one value per participant\n- `wd_id`: categorical, one value per word\n\n\nOur question is: **Does bigram frequency have a different effect on log RTs for high-frequency words and low-frequency words?**\n\nOur hypothesis might be:\n\n- High-frequency words will have fast RTs across the board, maybe even slightly faster when bigram frequency is also high.\n- But for low-frequency words, bigram frequency will make a big difference: RTs will be slower when bigram frequency is lower, and faster when bigram frequency is higher.\n\n(Is this actually true? idk!)\n\n## 1. Formulate the model\n\nThe maximal model is the following:\n\n`logRT ~ wdFreq * bigramFreq + (wdFreq * bigramFreq | ppt_id) + (1 | wd_id)`\n\n\n:::{.callout-tip collapse = 'true'}\n#### For the keen: Mathematical model specification\n\n**In words:**\n\n- Each participant $i$'s and word $j$'s log RT equals\n  - the intercept $\\beta_0$ plus each participant's intercept adjustment $u_{0i}$ plus eaach word's intercept adjustment $w_{0j}$; plus\n  - the slope over `wdFreq` $\\beta_1$ plus each participant's slope adjustment $u_{1i}$, all times `wdFreq`; plus\n  - the slope over `bigramFreq` $\\beta_2$ plus each participant's slope adjustment $u_{2i}$, all times `bigramFreq`; plus\n  - the slope over `wdFreq:bigramFreq` $\\beta_3$ plus each participant's interaction adjustment $u_{3i}$, all times `wdFreq` times `bigramFreq`; plus\n  - some error $\\epsilon$.\n- The error $\\epsilon$ is sampled from a Normal distribution with mean 0 and standard deviation (SD) $\\sigma$.\n- Each participant's adjustments to intercept $u_{0i}$, slopes $u_{1i}$ and $u_{2i}$, and interaction term $u_{3i}$, are sampled together from a multivariate Normal distribution.\n  - The mean of each dimension is 0.\n  - The spread of the distribution in each dimension is defined by a variance-covariance matrix with the variance (SD$^2$) of each adjustment on the diagonal and the correlations between those adjustments on the off-diagonals. Here the correlations are assumed to be zero.\n- Each word's adjustment to the intercept $w_{0j}$ is sampled from a Normal distribution with mean 0 and standard deviation $\\sigma_{w_{0j}}$.\n\n**In math:**\n\n$$\n\\begin{align}\n\\text{logRT}_{ij} =~& (\\beta_0 + u_{0i} + w_{0j}) ~ +  \\\\\n&  (\\beta_1 + u_{1i}) \\cdot \\text{wdFreq} ~ +  \\\\\n&  (\\beta_2 + u_{2i}) \\cdot \\text{bigramFreq} ~ +  \\\\\n&  (\\beta_3 + u_{3i}) \\cdot  \\text{wdFreq} \\cdot \\text{bigramFreq} + \\epsilon \\\\[.5em]\n\\epsilon \\sim~& \\text{Normal}(0, \\sigma) \\\\[.3em]\n\\pmatrix{u_{0i} \\\\ u_{1i} \\\\ u_{2i} \\\\ u_{3i}} \\sim~& \\text{Normal}\n\\begin{bmatrix}\n\\pmatrix{0 \\\\ 0 \\\\ 0 \\\\ 0},\n\\pmatrix{\n  \\sigma_{u_{0i}}^2 & 0 & 0 & 0\\\\ \n  0 & \\sigma_{u_{1i}}^2 & 0 & 0\\\\\n  0& 0 & \\sigma_{u_{2i}}^2  & 0\\\\\n  0 & 0 & 0 & \\sigma_{u_{3i}}^2\\\\\n  }\n\\end{bmatrix}\n\\\\\nw_{0j} \\sim~& \\text{Normal}(0, \\sigma_{w_{0j}})\n\\end{align}\n$$\n\n\n**Parameter glossary:**\n\n- $i$ indexes participants\n- $j$ indexes words\n- $\\beta_0$ is the intercept\n- $u_{0i}$ is the by-participant adjustment to intercept\n- $w_{0j}$ is the by-word adjustment to intercept\n- $\\beta_1$ is the slope over `wdFreq`\n- $u_{1i}$ is the by-participant adjustment to slope over `wdFreq`\n- $\\beta_2$ is the slope over `bigramFreq`\n- $u_{2i}$ is the by-participant adjustment to slope over `bigramFreq`\n- $\\beta_3$ is the interaction term between `wdFreq` and `bigramFreq`, i.e., how much the effect of one predictor changes with a change in the value of the other.\n- $u_{3i}$ is the by-participant adjustment to the interaction term\n- $\\epsilon$ is the error\n- $\\sigma$ is the SD of errors\n- $\\sigma_{u_{0i}}$ is the SD of by-participant intercept adjustment\n- $\\sigma_{u_{1i}}$ is the SD of by-participant slope adjustment to `wdFreq`\n- $\\sigma_{u_{2i}}$ is the SD of by-participant slope adjustment to `bigramFreq`\n- $\\sigma_{u_{3i}}$ is the SD of by-participant interaction adjustment\n- $\\sigma_{w_{0j}}$ is the SD of by-word intercept adjustment\n:::\n\n## 2. Define variable coding/transformation\n\n- `wdFreq`: \n  - As in Example 1, `low` frequency is coded as –0.5, `high` frequency as +0.5.\n  - The `wdFreq` parameter gives the effect of moving from `low` to `high` when `bigramFreq` = 0.\n- `bigramFreq`: \n  - The mean frequency of bigrams in each word, z-scored so that the mean is 0 and SD is 1. (Using z-scores makes simulating data super easy!)\n  - The `bigramFreq` parameter gives the effect of moving from mean bigram frequency to one SD above the mean for \"average\" `wdFreq`.\n- `Intercept`: \n  - Because both of the predictors are centered on 0, the intercept still represents the grand mean log RT.\n\n\n## 3. Simulate design matrix\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_ppts        <- 10  # same as in your pilot\nn_wds_per_ppt <- 10  # same as in your pilot + experiment\n\nset.seed(1)\nsimdat2 <- tibble(\n  ppt_id = rep(1:n_ppts, each = n_wds_per_ppt),\n  wd_id  = rep(1:n_wds_per_ppt, n_ppts),\n  wdFreq = rep(\n    c(\n      rep(-0.5, n_wds_per_ppt/2), \n      rep(0.5, n_wds_per_ppt/2)\n    ), n_ppts\n  ),\n  bigramFreq = rep(rnorm(n_wds_per_ppt, mean = 0, sd = 1), n_ppts)\n)\n\nsimdat2 |> head(20)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 20 × 4\n   ppt_id wd_id wdFreq bigramFreq\n    <int> <int>  <dbl>      <dbl>\n 1      1     1   -0.5     -0.626\n 2      1     2   -0.5      0.184\n 3      1     3   -0.5     -0.836\n 4      1     4   -0.5      1.60 \n 5      1     5   -0.5      0.330\n 6      1     6    0.5     -0.820\n 7      1     7    0.5      0.487\n 8      1     8    0.5      0.738\n 9      1     9    0.5      0.576\n10      1    10    0.5     -0.305\n11      2     1   -0.5     -0.626\n12      2     2   -0.5      0.184\n13      2     3   -0.5     -0.836\n14      2     4   -0.5      1.60 \n15      2     5   -0.5      0.330\n16      2     6    0.5     -0.820\n17      2     7    0.5      0.487\n18      2     8    0.5      0.738\n19      2     9    0.5      0.576\n20      2    10    0.5     -0.305\n```\n\n\n:::\n:::\n\n\n\n## 4. Define parameter values\n\n### (i) Grand mean\n\nLet's assume we've run a pilot study which tells us that the grand mean log RT is, again, 6.5 log units.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrand_mean <- 6.5\n```\n:::\n\n\n\n### (ii) Variance components\n\nLet's also assume that our pilot study has given us the following SDs for all the sources of variability in our new model:\n\n- by-participant adjustments to the intercept;\n- by-participant adjustments to the slope of `wdFreq`;\n- by-participant adjustments to the slope of `bigramFreq`;\n- by-participant adjustments to the interaction between `wdFreq` and `bigramFreq`;\n- by-word adjustments to the intercept; and\n- residual error.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsd_int_by_ppt <- 1.5\nsd_wdF_by_ppt <- 0.5\nsd_bgF_by_ppt <- 0.5\nsd_ixn_by_ppt <- 0.5\nsd_int_by_wd  <- 0.8\nsd_resid      <- 0.5\n```\n:::\n\n\nAt this point, let's also generate the variance-covariance matrix that `makeLmer()` will demand for the by-participant adjustments.\n(In real life, you would just extract this from the model fit to your pilot data; just look for the label `VarCorr` among the model's components.)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvcov_by_ppt <- matrix(data = 0, nrow = 4, ncol = 4)\ndiag(vcov_by_ppt) <- c(\n  sd_int_by_ppt^2,\n  sd_wdF_by_ppt^2,\n  sd_bgF_by_ppt^2,\n  sd_ixn_by_ppt^2\n)\nvcov_by_ppt\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     [,1] [,2] [,3] [,4]\n[1,] 2.25 0.00 0.00 0.00\n[2,] 0.00 0.25 0.00 0.00\n[3,] 0.00 0.00 0.25 0.00\n[4,] 0.00 0.00 0.00 0.25\n```\n\n\n:::\n:::\n\n\nEach adjustment's variance (SD$^2$) is on the diagonal, and the zeroes on the off-diagonals state that we're assuming that none of these adjustments are correlated with any other ones.\n\n\n\n\n### (iii) Effects of interest\n\nThis more complex model has three fixed effects: `wdFreq`, `bigramFreq`, and their interaction.\nDo we need to simulate different true effect sizes for all of them?\n\nLet's think about the question we're investigating:\n\n> Does bigram frequency have a different effect on log RTs for high-frequency words and low-frequency words?\n\n**That question can only be answered by looking at the interaction term.**\nAnd so our power analysis will focus on the interaction term too.\n\nHere's a fun fact that makes our lives easier: \n**the power properties of the interaction term don't seem to depend on the interacting predictors having specific values.**\nThis means that we don't need to simulate tons of combinations of different effects for `wdFreq` and `bigramFreq`.\nWe can just set them to some constant value and focus our computation on varying the size of the true interaction parameter, because no matter what value the interacting predictors have, the power properties of the interaction term will be the same.\n\n:::{.callout-tip collapse = 'true'}\n#### Don't believe me? Just plot\n\nHere are some plots from a related power analysis (but the results are different than what we'll get below!).\n<!-- This was from a development version in which I mistakenly simulated bigramFreq as within-word and not between-word oops! Cool to see the power consequences of that though! -->\n\n![](imgs/ixn_grid_power.png)\n\nThe facets in this plot show different combinations of true effect sizes for `wdFreq` and `bigramFreq`.\nBut in every single facet, the overall pattern is the same.\nWhat this suggests is that the power properties of the interaction term are unaffected by the values of the interacting predictors.\n:::\n\nLet's set `wdFreq` to –0.2 again.\nAnd let's set `bigramFreq` to –0.1.\n(Imagine that those are principled choices, based on pilots and previous literature!)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwdFreq_effect     <- -0.2\nbigramFreq_effect <- -0.1\n```\n:::\n\n\n\nNow, the interaction...\n\nInteractions are tricky to reason about at the best of times, and I find them extra unintuitive when predictors are centered.\nI used a little simulation-based trick to determine that, if our hypothesis is borne out, the interaction term should be positive (see the dropdown box below for details).\n\n:::{.callout-tip collapse = 'true'}\n#### How did I find the sign for the interaction term?\n\nI created a dataframe containing a basic constellation of mean log RTs that our hypothesis predicts.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsimmeans2 <- tibble(\n  wdFreq = c(-0.5, -0.5, 0.5, 0.5),\n  bigramFreq = c(-1, 1, -1, 1),\n  logRT = c(7, 6, 6, 5.8)\n)\n\nsimmeans2 |>\n  ggplot(aes(x = bigramFreq, y = logRT, colour = factor(wdFreq))) +\n  geom_point() +\n  geom_line() \n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-23-1.png){fig-align='center' width=672}\n:::\n:::\n\n\nThen I fit a simple linear model to this data.\nIt can't estimate any error, obviously, because the data contains none—but it will fit lines to the four data points provided.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lm(logRT ~ wdFreq * bigramFreq, data = simmeans2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = logRT ~ wdFreq * bigramFreq, data = simmeans2)\n\nResiduals:\nALL 4 residuals are 0: no residual degrees of freedom!\n\nCoefficients:\n                  Estimate Std. Error t value Pr(>|t|)\n(Intercept)            6.2        NaN     NaN      NaN\nwdFreq                -0.6        NaN     NaN      NaN\nbigramFreq            -0.3        NaN     NaN      NaN\nwdFreq:bigramFreq      0.4        NaN     NaN      NaN\n\nResidual standard error: NaN on 0 degrees of freedom\nMultiple R-squared:      1,\tAdjusted R-squared:    NaN \nF-statistic:   NaN on 3 and 0 DF,  p-value: NA\n```\n\n\n:::\n:::\n\n\nThis model summary tells me that if the data comes out looking the way we hypothesise, both conditional effects are negative and the interaction term is positive.\n\n(You could also use this trick to work out a reasonable SESOI for the interaction term!)\n\n:::\n\nLet's imagine that the interaction term's SESOI is 0.2 (the simulation-based trick from the dropdown box can help nail down this actual value too).\nAnd to better understand the power properties of the design, let's include a range of values on either side.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nixns_to_sim <- c(0.05, 0.1, 0.2, 0.5, 1)\n```\n:::\n\n\n\n\n\n## 5/6. Run power analysis, iterating over parameter values\n\nWe'll simulate a greater range of participant counts this time.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_ppts_to_sim2 <- c(40, 60, 80, 100, 120, 140, 160, 180, 200)\n```\n:::\n\n\n\nHere's the code to run the simulation! (For me, it takes 10–15 minutes to run.)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# define the accumulator \n# (we'll add a new row on each time)\npower_accumulator2 <- tibble(\n '40' = NA, \n '60' = NA, \n '80' = NA,\n '100' = NA,\n '120' = NA,\n '140' = NA,\n '160' = NA,\n '180' = NA,\n '200' = NA,\n 'mode' = NA,\n 'effect' = NA,\n 'true_ixn' = NA,\n)[0,]\n\n# iterate!\nfor(curr_ixn in ixns_to_sim){\n  \n  # set up the model with the current param estims \n  curr_model <- makeLmer(\n    formula = logRT ~ wdFreq * bigramFreq + \n      (1 + wdFreq * bigramFreq | ppt_id) + (1 | wd_id),\n    fixef = c(grand_mean, wdFreq_effect, bigramFreq_effect, curr_ixn),\n    sigma = sd_resid,\n    VarCorr = list(\n      # the four-dimension vcov matrix for the by-ppt adjustments\n      vcov_by_ppt, \n      # the variance of the by-word intercept adjustment\n      sd_int_by_wd^2\n    ),\n    data = simdat2\n  )\n  \n  # get power estims \n  curr_power <- mixedpower(\n    model = curr_model, \n    data = simdat2,\n    fixed_effects = c(\"wdFreq\", \"bigramFreq\"),\n    simvar = \"ppt_id\", \n    steps = n_ppts_to_sim2,\n    critical_value = 2, \n    n_sim = 1000\n  )\n  \n  # add current iteration's parameters\n  curr_power$true_ixn <- curr_ixn\n  \n  # add to accumulator\n  power_accumulator2 <- rbind(power_accumulator2, curr_power)\n  \n}\n```\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npower_accumulator2 |> kableExtra::kbl()  # unreadable without kable!\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\">   </th>\n   <th style=\"text-align:right;\"> 40 </th>\n   <th style=\"text-align:right;\"> 60 </th>\n   <th style=\"text-align:right;\"> 80 </th>\n   <th style=\"text-align:right;\"> 100 </th>\n   <th style=\"text-align:right;\"> 120 </th>\n   <th style=\"text-align:right;\"> 140 </th>\n   <th style=\"text-align:right;\"> 160 </th>\n   <th style=\"text-align:right;\"> 180 </th>\n   <th style=\"text-align:right;\"> 200 </th>\n   <th style=\"text-align:left;\"> mode </th>\n   <th style=\"text-align:left;\"> effect </th>\n   <th style=\"text-align:right;\"> true_ixn </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> wdFreq </td>\n   <td style=\"text-align:right;\"> 0.137 </td>\n   <td style=\"text-align:right;\"> 0.175 </td>\n   <td style=\"text-align:right;\"> 0.212 </td>\n   <td style=\"text-align:right;\"> 0.255 </td>\n   <td style=\"text-align:right;\"> 0.271 </td>\n   <td style=\"text-align:right;\"> 0.307 </td>\n   <td style=\"text-align:right;\"> 0.339 </td>\n   <td style=\"text-align:right;\"> 0.370 </td>\n   <td style=\"text-align:right;\"> 0.402 </td>\n   <td style=\"text-align:left;\"> databased </td>\n   <td style=\"text-align:left;\"> wdFreq </td>\n   <td style=\"text-align:right;\"> 0.05 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> bigramFreq </td>\n   <td style=\"text-align:right;\"> 0.095 </td>\n   <td style=\"text-align:right;\"> 0.124 </td>\n   <td style=\"text-align:right;\"> 0.125 </td>\n   <td style=\"text-align:right;\"> 0.169 </td>\n   <td style=\"text-align:right;\"> 0.177 </td>\n   <td style=\"text-align:right;\"> 0.178 </td>\n   <td style=\"text-align:right;\"> 0.187 </td>\n   <td style=\"text-align:right;\"> 0.221 </td>\n   <td style=\"text-align:right;\"> 0.212 </td>\n   <td style=\"text-align:left;\"> databased </td>\n   <td style=\"text-align:left;\"> bigramFreq </td>\n   <td style=\"text-align:right;\"> 0.05 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> wdFreq:bigramFreq </td>\n   <td style=\"text-align:right;\"> 0.070 </td>\n   <td style=\"text-align:right;\"> 0.074 </td>\n   <td style=\"text-align:right;\"> 0.089 </td>\n   <td style=\"text-align:right;\"> 0.096 </td>\n   <td style=\"text-align:right;\"> 0.089 </td>\n   <td style=\"text-align:right;\"> 0.099 </td>\n   <td style=\"text-align:right;\"> 0.099 </td>\n   <td style=\"text-align:right;\"> 0.105 </td>\n   <td style=\"text-align:right;\"> 0.099 </td>\n   <td style=\"text-align:left;\"> databased </td>\n   <td style=\"text-align:left;\"> wdFreq:bigramFreq </td>\n   <td style=\"text-align:right;\"> 0.05 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> wdFreq1 </td>\n   <td style=\"text-align:right;\"> 0.137 </td>\n   <td style=\"text-align:right;\"> 0.186 </td>\n   <td style=\"text-align:right;\"> 0.212 </td>\n   <td style=\"text-align:right;\"> 0.260 </td>\n   <td style=\"text-align:right;\"> 0.282 </td>\n   <td style=\"text-align:right;\"> 0.341 </td>\n   <td style=\"text-align:right;\"> 0.338 </td>\n   <td style=\"text-align:right;\"> 0.365 </td>\n   <td style=\"text-align:right;\"> 0.419 </td>\n   <td style=\"text-align:left;\"> databased </td>\n   <td style=\"text-align:left;\"> wdFreq </td>\n   <td style=\"text-align:right;\"> 0.10 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> bigramFreq1 </td>\n   <td style=\"text-align:right;\"> 0.101 </td>\n   <td style=\"text-align:right;\"> 0.142 </td>\n   <td style=\"text-align:right;\"> 0.137 </td>\n   <td style=\"text-align:right;\"> 0.154 </td>\n   <td style=\"text-align:right;\"> 0.171 </td>\n   <td style=\"text-align:right;\"> 0.208 </td>\n   <td style=\"text-align:right;\"> 0.215 </td>\n   <td style=\"text-align:right;\"> 0.202 </td>\n   <td style=\"text-align:right;\"> 0.240 </td>\n   <td style=\"text-align:left;\"> databased </td>\n   <td style=\"text-align:left;\"> bigramFreq </td>\n   <td style=\"text-align:right;\"> 0.10 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> wdFreq:bigramFreq1 </td>\n   <td style=\"text-align:right;\"> 0.088 </td>\n   <td style=\"text-align:right;\"> 0.106 </td>\n   <td style=\"text-align:right;\"> 0.098 </td>\n   <td style=\"text-align:right;\"> 0.105 </td>\n   <td style=\"text-align:right;\"> 0.113 </td>\n   <td style=\"text-align:right;\"> 0.128 </td>\n   <td style=\"text-align:right;\"> 0.115 </td>\n   <td style=\"text-align:right;\"> 0.128 </td>\n   <td style=\"text-align:right;\"> 0.136 </td>\n   <td style=\"text-align:left;\"> databased </td>\n   <td style=\"text-align:left;\"> wdFreq:bigramFreq </td>\n   <td style=\"text-align:right;\"> 0.10 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> wdFreq2 </td>\n   <td style=\"text-align:right;\"> 0.146 </td>\n   <td style=\"text-align:right;\"> 0.183 </td>\n   <td style=\"text-align:right;\"> 0.201 </td>\n   <td style=\"text-align:right;\"> 0.237 </td>\n   <td style=\"text-align:right;\"> 0.280 </td>\n   <td style=\"text-align:right;\"> 0.313 </td>\n   <td style=\"text-align:right;\"> 0.343 </td>\n   <td style=\"text-align:right;\"> 0.384 </td>\n   <td style=\"text-align:right;\"> 0.415 </td>\n   <td style=\"text-align:left;\"> databased </td>\n   <td style=\"text-align:left;\"> wdFreq </td>\n   <td style=\"text-align:right;\"> 0.20 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> bigramFreq2 </td>\n   <td style=\"text-align:right;\"> 0.106 </td>\n   <td style=\"text-align:right;\"> 0.123 </td>\n   <td style=\"text-align:right;\"> 0.122 </td>\n   <td style=\"text-align:right;\"> 0.159 </td>\n   <td style=\"text-align:right;\"> 0.172 </td>\n   <td style=\"text-align:right;\"> 0.195 </td>\n   <td style=\"text-align:right;\"> 0.194 </td>\n   <td style=\"text-align:right;\"> 0.215 </td>\n   <td style=\"text-align:right;\"> 0.237 </td>\n   <td style=\"text-align:left;\"> databased </td>\n   <td style=\"text-align:left;\"> bigramFreq </td>\n   <td style=\"text-align:right;\"> 0.20 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> wdFreq:bigramFreq2 </td>\n   <td style=\"text-align:right;\"> 0.125 </td>\n   <td style=\"text-align:right;\"> 0.137 </td>\n   <td style=\"text-align:right;\"> 0.139 </td>\n   <td style=\"text-align:right;\"> 0.195 </td>\n   <td style=\"text-align:right;\"> 0.189 </td>\n   <td style=\"text-align:right;\"> 0.230 </td>\n   <td style=\"text-align:right;\"> 0.220 </td>\n   <td style=\"text-align:right;\"> 0.240 </td>\n   <td style=\"text-align:right;\"> 0.262 </td>\n   <td style=\"text-align:left;\"> databased </td>\n   <td style=\"text-align:left;\"> wdFreq:bigramFreq </td>\n   <td style=\"text-align:right;\"> 0.20 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> wdFreq3 </td>\n   <td style=\"text-align:right;\"> 0.151 </td>\n   <td style=\"text-align:right;\"> 0.193 </td>\n   <td style=\"text-align:right;\"> 0.205 </td>\n   <td style=\"text-align:right;\"> 0.234 </td>\n   <td style=\"text-align:right;\"> 0.272 </td>\n   <td style=\"text-align:right;\"> 0.304 </td>\n   <td style=\"text-align:right;\"> 0.348 </td>\n   <td style=\"text-align:right;\"> 0.349 </td>\n   <td style=\"text-align:right;\"> 0.407 </td>\n   <td style=\"text-align:left;\"> databased </td>\n   <td style=\"text-align:left;\"> wdFreq </td>\n   <td style=\"text-align:right;\"> 0.50 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> bigramFreq3 </td>\n   <td style=\"text-align:right;\"> 0.100 </td>\n   <td style=\"text-align:right;\"> 0.139 </td>\n   <td style=\"text-align:right;\"> 0.141 </td>\n   <td style=\"text-align:right;\"> 0.152 </td>\n   <td style=\"text-align:right;\"> 0.157 </td>\n   <td style=\"text-align:right;\"> 0.201 </td>\n   <td style=\"text-align:right;\"> 0.196 </td>\n   <td style=\"text-align:right;\"> 0.212 </td>\n   <td style=\"text-align:right;\"> 0.236 </td>\n   <td style=\"text-align:left;\"> databased </td>\n   <td style=\"text-align:left;\"> bigramFreq </td>\n   <td style=\"text-align:right;\"> 0.50 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> wdFreq:bigramFreq3 </td>\n   <td style=\"text-align:right;\"> 0.297 </td>\n   <td style=\"text-align:right;\"> 0.404 </td>\n   <td style=\"text-align:right;\"> 0.472 </td>\n   <td style=\"text-align:right;\"> 0.533 </td>\n   <td style=\"text-align:right;\"> 0.645 </td>\n   <td style=\"text-align:right;\"> 0.697 </td>\n   <td style=\"text-align:right;\"> 0.721 </td>\n   <td style=\"text-align:right;\"> 0.767 </td>\n   <td style=\"text-align:right;\"> 0.809 </td>\n   <td style=\"text-align:left;\"> databased </td>\n   <td style=\"text-align:left;\"> wdFreq:bigramFreq </td>\n   <td style=\"text-align:right;\"> 0.50 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> wdFreq4 </td>\n   <td style=\"text-align:right;\"> 0.136 </td>\n   <td style=\"text-align:right;\"> 0.189 </td>\n   <td style=\"text-align:right;\"> 0.221 </td>\n   <td style=\"text-align:right;\"> 0.230 </td>\n   <td style=\"text-align:right;\"> 0.276 </td>\n   <td style=\"text-align:right;\"> 0.321 </td>\n   <td style=\"text-align:right;\"> 0.322 </td>\n   <td style=\"text-align:right;\"> 0.382 </td>\n   <td style=\"text-align:right;\"> 0.403 </td>\n   <td style=\"text-align:left;\"> databased </td>\n   <td style=\"text-align:left;\"> wdFreq </td>\n   <td style=\"text-align:right;\"> 1.00 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> bigramFreq4 </td>\n   <td style=\"text-align:right;\"> 0.095 </td>\n   <td style=\"text-align:right;\"> 0.125 </td>\n   <td style=\"text-align:right;\"> 0.139 </td>\n   <td style=\"text-align:right;\"> 0.154 </td>\n   <td style=\"text-align:right;\"> 0.173 </td>\n   <td style=\"text-align:right;\"> 0.184 </td>\n   <td style=\"text-align:right;\"> 0.204 </td>\n   <td style=\"text-align:right;\"> 0.210 </td>\n   <td style=\"text-align:right;\"> 0.236 </td>\n   <td style=\"text-align:left;\"> databased </td>\n   <td style=\"text-align:left;\"> bigramFreq </td>\n   <td style=\"text-align:right;\"> 1.00 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> wdFreq:bigramFreq4 </td>\n   <td style=\"text-align:right;\"> 0.746 </td>\n   <td style=\"text-align:right;\"> 0.875 </td>\n   <td style=\"text-align:right;\"> 0.931 </td>\n   <td style=\"text-align:right;\"> 0.970 </td>\n   <td style=\"text-align:right;\"> 0.986 </td>\n   <td style=\"text-align:right;\"> 0.993 </td>\n   <td style=\"text-align:right;\"> 0.997 </td>\n   <td style=\"text-align:right;\"> 1.000 </td>\n   <td style=\"text-align:right;\"> 1.000 </td>\n   <td style=\"text-align:left;\"> databased </td>\n   <td style=\"text-align:left;\"> wdFreq:bigramFreq </td>\n   <td style=\"text-align:right;\"> 1.00 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\nNotice that we get power estimates for `wdFreq` and `bigramFreq` too, how nice.\n\nI for one can't just look at a grid of numbers and understand what's happening.\nSo let's plot it.\n\nLet's first wrangle the data into tall format:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npower2_tall <- power_accumulator2 |>\n  pivot_longer(\n    cols = as.character(n_ppts_to_sim2),\n    names_to = 'n_ppts',\n    values_to = 'power'\n  ) |>\n  mutate(\n    n_ppts = factor(n_ppts, levels = n_ppts_to_sim2),\n    true_ixn = factor(true_ixn, levels = ixns_to_sim)\n  )\n\npower2_tall |> head()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  mode      effect true_ixn n_ppts power\n  <chr>     <chr>  <fct>    <fct>  <dbl>\n1 databased wdFreq 0.05     40     0.137\n2 databased wdFreq 0.05     60     0.175\n3 databased wdFreq 0.05     80     0.212\n4 databased wdFreq 0.05     100    0.255\n5 databased wdFreq 0.05     120    0.271\n6 databased wdFreq 0.05     140    0.307\n```\n\n\n:::\n:::\n\n\n\nAnd now let's plot!\n\n\n::: {.cell}\n\n```{.r .cell-code}\npower2_tall |>\n  filter(effect == 'wdFreq:bigramFreq') |>\n  mutate(true_ixn = factor(true_ixn)) |>\n  ggplot(aes(x = n_ppts, y = power, colour = true_ixn)) +\n  geom_point() +\n  geom_line(aes(group = true_ixn)) +\n  ylim(0, 1) +\n  geom_hline(yintercept = 0.8, linetype = 'dotted') +\n  labs(\n    title = 'power of wdFreq:bigramFreq'\n  ) +\n  NULL\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n\nOof!\n\n:::yellow\n🧠✨\nWhat does this power analysis tell us about the power of our interaction term?\n:::\n\n\n:::{.callout-tip collapse='true'}\n#### Power plots for `wdFreq` and `bigramFreq`\n\nHere are the analogous plots showing the power of the other two fixed effects:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(patchwork)\n\np_wdF <- power2_tall |>\n  filter(effect == 'wdFreq') |>\n  mutate(true_ixn = factor(true_ixn)) |>\n  ggplot(aes(x = n_ppts, y = power, colour = true_ixn)) +\n  geom_point() +\n  geom_line(aes(group = true_ixn)) +\n  # facet_grid(true_bigramFreq ~ true_wdFreq, labeller = label_both) +\n  ylim(0, 1) +\n  geom_hline(yintercept = 0.8, linetype = 'dotted') +\n  labs(\n    title = 'power of wdFreq'\n  ) +\n  NULL\n\np_bgF <- power2_tall |>\n  filter(effect == 'bigramFreq') |>\n  mutate(true_ixn = factor(true_ixn)) |>\n  ggplot(aes(x = n_ppts, y = power, colour = true_ixn)) +\n  geom_point() +\n  geom_line(aes(group = true_ixn)) +\n  ylim(0, 1) +\n  geom_hline(yintercept = 0.8, linetype = 'dotted') +\n  labs(\n    title = 'power of bigramFreq'\n  ) +\n  NULL\n\np_wdF + p_bgF + plot_layout(guides = 'collect')\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-30-1.png){fig-align='center' width=768}\n:::\n:::\n\n\nAssuming the true effect sizes we set above, these parameters are really low-powered.\nArguably though, if our hypothesis doesn't hinge on rejecting the H0 for these parameters, then maybe this is okay?\nWhat's more important is the power of our interaction term (which unfortunately is also a little dismal...).\n\nAlso, notice how the value of the interaction term doesn't really make a difference for the power of these effects.\n:::\n\n\n# Questions you submitted\n\n:::{.callout-note collapse = 'true'}\n#### How would you report and describe a power analysis (in a paper)?\n\n- Different folks have different styles.\n- I would keep the body of the paper streamlined and only go into greater detail in the appendix/supplementary materials/OSF project/whatever extra bonus thing.\n- For example, in the body of the paper, I might write something like\n\n> We aimed to collect analysable data from [N] participants, because our a priori power analysis indicated that with [N] participants, we could identify a true effect of size [X] with 80% power (see Appendix A).\nWe recruited a total of [N+x] participants to account for attrition, exclusion, etc., and ended up analysing data from [N–y] participants.\n\n- and then in Appendix A, I'd include a prose description of the process and plots like the ones above. \n- And if you already share your analysis code online, then definitely share the power analysis code too.\n:::\n\n\n:::{.callout-note collapse = 'true'}\n#### How do you decide what kind of model to run for simulating the data for power analysis? What if the ideal model does not converge? / Could we discuss [...] min vs max model construction?\n\n- I recommend using the maximal model for the power analysis, even if you ultimately can't fit that model to your real data because of convergence issues etc.\n  - Why use the maximal model? Because maximal models are the most conservative possible model, and they have lower statistical power compared to simpler models (see [Matuschek et al., 2017](https://www.sciencedirect.com/science/article/pii/S0749596X17300013)).\n  - In other words, the maximal model will give you a larger estimate of how many participants you need to have a well-powered statistical test than a simpler model would.\n- So even if you have convergence issues in your real model and need to simplify, then as long as you you collected the amount of data that makes the maximal model well-powered, your simpler model should be even more well-powered.\n:::\n\n:::{.callout-note collapse = 'true'}\n#### Could we discuss when to do model comparisons and when to do just summaries to interpret what has a significant effect?\n\t\n- For me, this choice really depends on the research question/hypothesis that you're testing.\n  - If your research question can best be answered by finding out whether one model is a significant improvement over the other, then model comparisons are the way to go; e.g.,\n    - \"Is X a useful predictor of Y?\"\n    - \"Does Z explain a significant amount of variance in Y, over and above the variance explained by X?\"\n  - If your research question can best be answered by finding out whether some model parameter is significantly different from zero, then parameter testing is the way to go; e.g.,\n    - \"Is the grand mean of Y significantly different from zero?\"\n    - \"Is a change in X significantly associated with a change in Y?\"\n- I haven't done simulation-based power analyses for model comparison before, but I imagine the same principles should hold:\n  - simulate data that you declare to represent the real world;\n  - fit both models to that data and make a model comparison decision;\n  - do those steps a bunch of times and see what proportion of the time the model comparison test rejects the H0.\n\n:::\n\n\n# Additional resources\n\n- [Kumle et al.'s notebook walkthroughs of `mixedpower`](https://lkumle.github.io/power_notebooks/)\n- [Video lectures from Shravan Vasishth's fantastic intro stats course](https://vasishth.github.io/IntroductionStatistics/); the four-part lesson 12 is all about simulating data and running power analyses\n\n\n# Session info\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.5.2 (2025-10-31)\nPlatform: aarch64-apple-darwin20\nRunning under: macOS Sequoia 15.7.3\n\nMatrix products: default\nBLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib \nLAPACK: /Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1\n\nlocale:\n[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8\n\ntime zone: Europe/London\ntzcode source: internal\n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n [1] patchwork_1.3.2  mixedpower_0.1.0 simr_1.0.8       lme4_1.1-38     \n [5] Matrix_1.7-4     lubridate_1.9.4  forcats_1.0.1    stringr_1.6.0   \n [9] dplyr_1.2.0      purrr_1.2.1      readr_2.1.6      tidyr_1.3.2     \n[13] tibble_3.3.1     ggplot2_4.0.1    tidyverse_2.0.0 \n\nloaded via a namespace (and not attached):\n [1] gtable_0.3.6       xfun_0.56          htmlwidgets_1.6.4  lattice_0.22-7    \n [5] tzdb_0.5.0         vctrs_0.7.1        tools_4.5.2        Rdpack_2.6.5      \n [9] generics_0.1.4     parallel_4.5.2     pbkrtest_0.5.5     pkgconfig_2.0.3   \n[13] RColorBrewer_1.1-3 S7_0.2.1           lifecycle_1.0.5    binom_1.1-1.1     \n[17] compiler_4.5.2     farver_2.1.2       textshaping_1.0.4  carData_3.0-6     \n[21] htmltools_0.5.9    yaml_2.3.12        Formula_1.2-5      pillar_1.11.1     \n[25] car_3.1-3          nloptr_2.2.1       MASS_7.3-65        reformulas_0.4.4  \n[29] iterators_1.0.14   boot_1.3-32        abind_1.4-8        nlme_3.1-168      \n[33] tidyselect_1.2.1   digest_0.6.39      stringi_1.8.7      labeling_0.4.3    \n[37] splines_4.5.2      fastmap_1.2.0      grid_4.5.2         RLRsim_3.1-9      \n[41] cli_3.6.5          magrittr_2.0.4     utf8_1.2.6         broom_1.0.12      \n[45] withr_3.0.2        scales_1.4.0       backports_1.5.0    plotrix_3.8-14    \n[49] timechange_0.4.0   rmarkdown_2.30     otel_0.2.0         hms_1.1.4         \n[53] kableExtra_1.4.0   evaluate_1.0.5     knitr_1.51         rbibutils_2.4.1   \n[57] viridisLite_0.4.2  mgcv_1.9-4         rlang_1.1.7        Rcpp_1.1.1        \n[61] glue_1.8.0         xml2_1.5.2         svglite_2.2.2      rstudioapi_0.18.0 \n[65] minqa_1.2.8        jsonlite_2.0.0     plyr_1.8.9         R6_2.6.1          \n[69] systemfonts_1.3.1 \n```\n\n\n:::\n:::\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../../site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"../../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}